import { createFileRoute } from "@tanstack/react-router";
import { Download, Film, KeyRound, Loader2, RefreshCw, ShieldCheck, SlidersHorizontal, Sparkles, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { GradientCard } from "@/components/gradient-card";
import { clearPersonalAiSettings, getPersonalAiSettings, savePersonalAiSettings, testPersonalAi, type PersonalProvider } from "@/lib/ai-router";
import { getPreferences, setPreferences, type Preferences } from "@/lib/clipforge-client";

export const Route = createFileRoute("/_authenticated/settings")({ head: () => ({ meta: [{ title: "Settings — ClipForge" }] }), component: SettingsPage });
type ReleaseInfo = { tag_name: string; html_url: string; assets?: Array<{ name: string; browser_download_url: string }> };
function currentAppVersion() { const native = (window as unknown as { ClipForgeNative?: { getAppVersion?: () => string } }).ClipForgeNative; try { const value = native?.getAppVersion?.(); if (value) return value; } catch {} return navigator.userAgent.match(/(?:^|\s)ClipForge\/([^\s]+)/)?.[1] ?? "web"; }
function parts(value: string) { return value.replace(/^v/i, "").split(/[.-]/).map(Number).filter(Number.isFinite).slice(0, 3); }
function newer(latest: string, installed: string) { if (installed === "web") return false; const a = parts(latest), b = parts(installed); for (let i = 0; i < Math.max(a.length,b.length); i++) { const diff = (a[i] ?? 0) - (b[i] ?? 0); if (diff) return diff > 0; } return false; }

function SettingsPage() {
  const initialAi = useMemo(getPersonalAiSettings, []);
  const [prefs, setPrefs] = useState<Preferences>(() => getPreferences()), [checking, setChecking] = useState(false), [release, setRelease] = useState<ReleaseInfo | null>(null);
  const [provider,setProvider] = useState<PersonalProvider>(initialAi.provider), [baseUrl,setBaseUrl] = useState(initialAi.baseUrl || ""), [apiKey,setApiKey] = useState(""), [hasKey,setHasKey] = useState(initialAi.hasKey), [testing,setTesting] = useState(false), [aiStatus,setAiStatus] = useState("");
  const installed = useMemo(currentAppVersion, []), updateAvailable = release ? newer(release.tag_name, installed) : false;
  function patch(value: Partial<Preferences>) { const next = setPreferences(value); setPrefs(next); }
  async function checkUpdate() {
    setChecking(true);
    try { const response = await fetch("https://api.github.com/repos/WynnDev-rill/auto-vid-clipper/releases/latest", { headers: { Accept: "application/vnd.github+json" }, cache: "no-store" }); if (!response.ok) throw new Error(`Update check failed (${response.status})`); const latest = await response.json() as ReleaseInfo; setRelease(latest); toast.success(newer(latest.tag_name, installed) ? `${latest.tag_name} is available` : "ClipForge is up to date"); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Could not check updates"); } finally { setChecking(false); }
  }
  function installUpdate() { if (!release) return; const apk = release.assets?.find((asset) => asset.name.toLowerCase().endsWith(".apk")); const url = apk?.browser_download_url ?? release.html_url; const native = (window as unknown as { ClipForgeNative?: { openUpdateUrl?: (url: string) => void } }).ClipForgeNative; try { if (native?.openUpdateUrl) native.openUpdateUrl(url); else window.open(url, "_blank", "noopener,noreferrer"); } catch { window.location.assign(release.html_url); } }
  async function testAndSave() {
    if (!apiKey.trim() && !hasKey) return toast.error("Enter an API key first.");
    setTesting(true); setAiStatus("");
    try { savePersonalAiSettings({provider,baseUrl,apiKey}); const result=await testPersonalAi({provider,baseUrl,apiKey}); setHasKey(true); setApiKey(""); setAiStatus(`${result.provider}${result.chatModel ? ` · Chat: ${result.chatModel}` : ""}${result.speechModel ? ` · Speech: ${result.speechModel}` : ""}`); toast.success(result.message); }
    catch(e){ toast.error(e instanceof Error?e.message:"Could not test this API"); } finally { setTesting(false); }
  }
  function removeKey(){ clearPersonalAiSettings(); setHasKey(false); setApiKey(""); setAiStatus(""); setProvider("auto"); setBaseUrl(""); toast.success("Personal AI fallback removed"); }
  return <div className="mx-auto max-w-2xl space-y-5">
    <div><p className="text-xs uppercase tracking-wide text-muted-foreground">ClipForge</p><h1 className="font-display text-2xl font-semibold md:text-3xl">Settings</h1></div>
    <GradientCard><div className="flex items-start gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-gradient-brand shadow-glow"><Download size={18} className="text-primary-foreground" /></div><div className="min-w-0 flex-1"><p className="font-semibold">App update</p><p className="mt-1 text-sm text-muted-foreground">Installed: {installed === "web" ? "Web app" : `v${installed}`}</p>{release ? <p className={`mt-1 text-xs ${updateAvailable ? "text-brand-cyan" : "text-muted-foreground"}`}>{updateAvailable ? `${release.tag_name} is ready` : `Latest: ${release.tag_name}`}</p> : null}<div className="mt-3 flex gap-2"><button onClick={checkUpdate} disabled={checking} className="inline-flex items-center gap-1.5 rounded-full border border-border px-3 py-1.5 text-xs font-semibold">{checking ? <Loader2 size={12} className="animate-spin" /> : <RefreshCw size={12} />} Check update</button>{updateAvailable ? <button onClick={installUpdate} className="rounded-full bg-gradient-brand px-3 py-1.5 text-xs font-semibold text-primary-foreground">Update</button> : null}</div></div></div></GradientCard>

    <GradientCard glow><div className="mb-4 flex items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-primary/10"><KeyRound size={18} className="text-brand-cyan" /></div><div><p className="font-semibold">Personal AI fallback <span className="text-xs font-normal text-muted-foreground">· optional</span></p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Normally ClipForge rotates remote community/free AI automatically. Add one personal key only as an emergency fallback. You never choose a model; ClipForge discovers a suitable free or free-tier model automatically and refreshes it if the model disappears.</p></div></div>
      <div className="space-y-3"><label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">Provider</span><select value={provider} onChange={(e)=>setProvider(e.target.value as PersonalProvider)} className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm"><option value="auto">Auto detect</option><option value="groq">Groq</option><option value="openrouter">OpenRouter</option><option value="gemini">Google Gemini</option><option value="custom">Custom OpenAI-compatible</option></select></label>
      {provider==="custom"?<label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">Base URL</span><input value={baseUrl} onChange={(e)=>setBaseUrl(e.target.value)} inputMode="url" placeholder="https://api.example.com/v1" className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm outline-none focus:border-primary" /></label>:null}
      <label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">API key</span><input value={apiKey} onChange={(e)=>setApiKey(e.target.value)} type="password" autoComplete="off" spellCheck={false} placeholder={hasKey?"Saved securely — enter a new key to replace it":"Paste API key"} className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm outline-none focus:border-primary" /></label>
      <div className="flex flex-wrap items-center gap-2"><button onClick={testAndSave} disabled={testing} className="inline-flex items-center gap-2 rounded-full bg-gradient-brand px-4 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50">{testing?<Loader2 size={13} className="animate-spin"/>:<ShieldCheck size={13}/>} Test & save</button>{hasKey?<button onClick={removeKey} className="inline-flex items-center gap-1.5 rounded-full border border-destructive/30 px-3 py-2 text-xs text-destructive"><Trash2 size={12}/> Remove key</button>:null}</div>
      {aiStatus?<p className="rounded-xl bg-secondary/60 px-3 py-2 text-[11px] leading-relaxed text-muted-foreground">{aiStatus}</p>:null}<p className="text-[11px] leading-relaxed text-muted-foreground">On Android, the key is encrypted with Android Keystore and is never sent to ClipForge, Render, or GitHub. It is sent directly only to the provider you selected when the automatic pool is unavailable.</p></div>
    </GradientCard>

    <GradientCard><div className="mb-4 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-secondary"><SlidersHorizontal size={17} /></div><div><p className="font-semibold">Default export</p><p className="text-xs text-muted-foreground">Used by quick export; each moment can still be edited.</p></div></div><div className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">Aspect ratio</span><select value={prefs.aspectRatio} onChange={(e) => patch({ aspectRatio: e.target.value as Preferences["aspectRatio"] })} className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm"><option value="9:16">9:16 · Shorts / Reels / TikTok</option><option value="1:1">1:1 · Square</option><option value="16:9">16:9 · Landscape</option></select></label><label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">Caption style</span><select value={prefs.captionStyle} onChange={(e) => patch({ captionStyle: e.target.value as Preferences["captionStyle"] })} className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm"><option value="modern">Modern</option><option value="bold">Bold</option><option value="minimal">Minimal</option></select></label><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Captions" value={prefs.captions} onChange={(value) => patch({ captions: value })} /><Toggle label="Normalize audio" value={prefs.normalizeAudio} onChange={(value) => patch({ normalizeAudio: value })} /></div><label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">Framing</span><select value={prefs.cropMode} onChange={(e) => patch({ cropMode: e.target.value as Preferences["cropMode"] })} className="w-full rounded-xl border border-input bg-input/30 px-3 py-2.5 text-sm"><option value="safe">Safe · keep full subject visible</option><option value="fill">Fill · crop to frame</option></select></label></div></GradientCard>
    <GradientCard><div className="flex items-start gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-secondary"><Sparkles size={18} /></div><div><p className="font-semibold">Automatic AI routing</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Remote speech and moment analysis try no-key/community providers first and automatically fail over. If all remote AI fails, deterministic non-AI scoring still produces basic candidates. No AI model is downloaded to your phone.</p></div></div></GradientCard>
    <GradientCard><div className="flex items-start gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-secondary"><Film size={18} /></div><div><p className="font-semibold">Local processing & storage</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Source uploads, project state, editing and final rendering stay on this device. URL resolving uses a lightweight serverless resolver; video processing no longer depends on a Render worker.</p></div></div></GradientCard>
  </div>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <button onClick={() => onChange(!value)} className="flex items-center justify-between rounded-xl border border-border bg-card/40 px-3 py-2.5 text-sm"><span>{label}</span><span className={`h-6 w-11 rounded-full p-1 ${value ? "bg-primary" : "bg-secondary"}`}><span className={`block size-4 rounded-full bg-white transition ${value ? "translate-x-5" : ""}`} /></span></button>; }
